spring:
  datasource:
    url: jdbc:mysql://localhost:3306/storetable?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: subinha
    password: zerobase
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true


# hikari와 관련된 설정은 선택적으로 적용할 수 있음
# HikariCP는 Spring Boot에서 기본적으로 사용되는 데이터베이스 커넥션 풀 라이브러리
# data-source-properties 아래의 설정은 HikariCP의 특정 기능을 활성화하고 조정하는 데 사용됨
# 각 설정의 역할은 다음과 같다.

# cachePrepStmts: Prepared Statement를 캐시에 저장할지 여부를 결정
# 캐시에 저장하면 Prepared Statement를 재사용하여 성능을 향상시킬 수 있음. 기본값은 false
# 이 설정은 일반적으로 성능 향상을 위해 사용됨.

# prepStmtCacheSize: Prepared Statement 캐시의 크기를 지정
# 캐시에 저장할 Prepared Statement 의 최대 개수를 의미. 기본값은 250

# prepStmtCacheSqlLimit: Prepared Statement 캐시에 저장할 SQL의 최대 길이를 지정
# 길이를 초과하는 SQL은 캐시되지 않는다. 기본값은 2048

#useServerPrepStmts: 서버 측 Prepared Statement를 사용할지 여부를 결정
# 서버 측 Prepared Statement는 MySQL에서 지원하는 기능으로,
# 클라이언트에서 Prepared Statement를 준비하는 대신 서버에서 직접 처리. 기본값은 true

# 이러한 설정은 애플리케이션의 성능을 향상시키기 위해 사용될 수 있음.
# 하지만 모든 상황에 적합한 것은 아니며, 필요에 따라 설정을 변경하거나 제거할 수 있음.
# 설정을 사용할지 여부는 애플리케이션의 특정 요구 사항과 성능 향상을 위한 실험 결과를 고려하여 결정해야 함.



